### ISSUE TITLE
About "margin" and "num_negative_samples" hyperparames when training embedding based models

### ISSUE THREAD

**Issue by David-Lee-1990** [salesforce/MultiHopKG#13]
Hi,  as discussed in  #3 , training embedding models uses BCEloss. But the hyperparames given in the config file still have margin and num_negative_samples. Why? The following is "fb15k-237-complex.sh"

`#!/usr/bin/env bash

data_dir="data/FB15K-237"
model="complex"
add_reversed_training_edges="True"
group_examples_by_query="True"
entity_dim=200
relation_dim=200
num_rollouts=1
bucket_interval=10
num_epochs=1000
num_wait_epochs=500
batch_size=512
train_batch_size=512
dev_batch_size=128
learning_rate=0.003
grad_norm=5
emb_dropout_rate=0.3
beam_size=128
num_negative_samples=50
margin=10`

Another question, when i set num_peek_epochs = n where n may equals 10, 100, etc. The program for training embedding based model always train 2n epochs and stop.  I connot figure it out. Can you give me some help?

**Comment by todpole3** [comment]
The `margin` and `num_negative_samples` parameters were just there for other experiment settings. For the setup reported in our paper they are dummy parameters.

**Comment by David-Lee-1990** [comment]
@todpole3  Thank you for replying.
