### ISSUE TITLE
Problem with output model files

### ISSUE THREAD

**Issue by msaebi19993** [salesforce/MultiHopKG#14]
Hi,

I'm having an issue with opening the output model files and checkpoints. I have trained the RL models for the Kinship dataset. However, the output checkpoints and model_best tar files seem to be corrupted. Do you know why this might happen?
Also, how can I print the paths taken by the agent?

**Comment by todpole3** [comment]
@msaebi19993 Could you post the error message?

**Comment by msaebi19993** [comment]
I just realized that these are not actually .tar files so I should use torch.load() to load the model at that checkpoint. I'm new to pytorch so I assumed that they are compressed files containing the final results. 
Could you please explain how can I see the output paths taken by the agent?

**Comment by todpole3** [comment]
Please try the `--save_beam_search_paths` flag mentioned here:
https://github.com/salesforce/MultiHopKG#evaluate-pretrained-models

**Comment by todpole3** [comment]
Please reopen if you have further questions.

**Comment by msaebi1993** [comment]
Thanks for your help!
