### ISSUE TITLE
NELL-995 dataset

### ISSUE THREAD

**Issue by Ashappyboy** [salesforce/MultiHopKG#20]
hi,
I see that you publish two NELL 995 dataset which includes NELL-995 dataset and NELL-995.test.  
As you said, the "train.large.triples = raw.kb - dev.triple" and "train.dev.triples is the training file from the original data" and "train.dev.large.triples = raw.kb".
So, I want to ask what is the meaning of doing that?
and I want to find the original NELL-995 dataset but I failed. So, if you get the dataset, could you share the link with me. 
I will appreciate it If you could help me. 
Best wishes!

**Comment by godidier** [comment]
For anyone else looking for the NELL995 dataset, there is a link in this presentation  by [Wenhan Xiong](https://xwhan.github.io/docs/emnlp2017.pptx) that point to the dataset : http://cs.ucsb.edu/~xwhan/datasets/NELL-995.zip
