### ISSUE TITLE
about the function of nell split

### ISSUE THREAD

**Issue by Ashappyboy** [salesforce/MultiHopKG#21]
Hi, I have read your NELL data readme. And I have some problem to consult you. I don't know the meaning to split the dataset. Why don't just divide the dataset into train, dev, test. Can you explain it? 
Thank you very much.
And in detail, I open the raw.kb and just found the 150222 lines which are not same as your introduction in your paper. I'm not sure the reason.
Best wishes!

**Comment by todpole3** [comment]
The number reported in the paper is the total lines in raw.kb + test.triples.

We don't do the a three-way split ourselves because there is a given test set (test.triples).
