### ISSUE TITLE
the meaning of NELL split

### ISSUE THREAD

**Issue by Ashappyboy** [salesforce/MultiHopKG#22]
Hi, thank you for your reply.
![image](https://user-images.githubusercontent.com/31423097/91113089-4b99dd80-e6b7-11ea-912b-41b4cc9a5821.png)
just as the spotimage and you have said, I think that you can split the raw into the train which should get some new triples from raw.kb and dev. So, from the image, I found many overlop and development dataset is belong to the test dataset. 
hence, I want to consult for you why do this and the work of that.
Bese regards!

**Comment by todpole3** [comment]
I'm afraid I do not fully understand your question.

If you check the files we provided, the dev and test triples do not overlap. 
```
data/NELL-995# comm -12 <(sort dev.triples) <(sort test.triples)
```

Hence I'm not sure what you mean by "I found many overlop and development dataset is belong to the test dataset."

**Comment by Ashappyboy** [comment]
thank you for your reply.
I mean that the development process and the test process have overlap. 
And I can sure which dataset you use in the development process and the test process but I don't know the meaning of split the dataset into that.  I can sure that the test.triples is not included in the raw.kb. 
Meanwhile, I confused about the mode including the development process and test process. Can you explain which dataset we have to use in the development process or test process and which work we have to do in the development or test process?
Bese regards!
