### ISSUE TITLE
Questions about nell-995 and nell-995.test 关于nell-995和nell-995.test的问题

### ISSUE THREAD

**Issue by BlackLucy** [salesforce/MultiHopKG#29]
The code only provides the .test file of the nell-995 data set. What is the difference between these two data sets?
How to generate .test files for other data sets? 

代码只提供了nell-995数据集的.test文件，请问这两个数据集有什么区别？
请问其他数据集的.test文件如何生成？

**Comment by todpole3** [comment]
For the other datasets we used the data released here: https://github.com/shehzaadzd/MINERVA/tree/master/datasets/data_preprocessed

**Comment by yzj19870824** [comment]
> The code only provides the .test file of the nell-995 data set. What is the difference between these two data sets?
> How to generate .test files for other data sets?
> 
> 代码只提供了nell-995数据集的.test文件，请问这两个数据集有什么区别？
> 请问其他数据集的.test文件如何生成？

你能够正常训练不？不是embedding阶段，而是train阶段
