### ISSUE TITLE
How to prepare page ranks?

### ISSUE THREAD

**Issue by Toni-Chan** [salesforce/MultiHopKG#4]
We are migrating other datasets for testing on your model. We noticed that in each of the datasets you supplied there is a raw.pgrk file. How do you generate the file?

**Comment by todpole3** [comment]
The raw.pgrk files are generated using the source code from this repo: 
https://github.com/timothyasp/PageRank

We computed the undirectional page rank (for each original edge in the base graph I added its reverse edge) with uniform node weights.

**Comment by Toni-Chan** [comment]
Thanks
