### ISSUE TITLE
about entity2id.txt

### ISSUE THREAD

**Issue by SJIANAN** [salesforce/MultiHopKG#6]
Hi, I read your paper and codes and there is a confusion.
In entity2id.txt, the value of ID is number of occurrences of entities, What is the reason for this?

**Comment by todpole3** [comment]
The entity frequencies are stored in `entity2id.txt` simply to make it easier for me to check the graph statistics. In our model we index the entities based on their order of occurrence in `entity2id.txt`. The procedure for creating entity and relation index is implemented in the `load_index` function here:

https://github.com/salesforce/MultiHopKG/blob/master/src/data_utils.py#L175
