### ISSUE TITLE
Question about the input

### ISSUE THREAD

**Issue by SJIANAN** [salesforce/MultiHopKG#8]
Hi, In  Knowledge Graph Reasoning,  What exactly is the format of  the input? This question plagued me for a long time.
in dataset，（es,r,ed) is the triple contained in the dataset,  (es, rq, ?) is  a query.
In training process, what is the input?  (es,rq,eT) or (es,r,ed)? 
if (es,r,ed) is input, the Reasoning path is (es,r,ed)-->(ed,r,ed1)-->(ed1,r,ed2)? 
How do we determine the size of the reward at the end time T? according  whether ed2 equals eT? 
in test time, what is the input?
Thanks!

**Comment by todpole3** [comment]
At training time, the input is `(es, rq, eT)`. 

When using `(es, rq, eT)` as the input, the reasoning path is `(es, r1, e1)->(e1,r2,e2)->...->(en,rn+1,en+1)`.

Yes, the reward is determined by whether `en+1` equals to `eT`. You may also refer to our paper for a way of determining the reward based on a function of`es, rq, en+1`.

At test time, the input is `(es, rq)`.
